accept = [200, 204, 206, 301, 302, 303, 307, 308]
exclude = [
  '^mailto:',
  '^tel:',
  '^https://kubernetes\.io/docs/reference/using-api/$'
]
exclude_path = [
  'docs/books/postgresql-sre-dbre-handbook',
  'docs/books/snowflake',
  'docs/books/terraform'
]
max_retries = 2
timeout = 20
